StateMachine:
  Type: AWS::StepFunctions::StateMachine
  DependsOn: StepFunctionsExecutionRole
  Properties:
    DefinitionString: |-
      {
        "Comment": "Migrate articles from MongoDb to DynamoDB",
        "StartAt": "Get Last Imported Article",
        "States": {
          "Get Last Imported Article": {
            "Type":"Task",
            "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-getLastImportedArticle",
            "ResultPath":"$.lastImport",
            "Next":"Get Articles Since Last Import"
          },
          "Get Articles Since Last Import":{
            "Type":"Task",
            "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-getArticlesSinceLastImport",
            "ResultPath":"$.articles",
            "Next":"Migrate Articles",
            "Catch":[
              {
                "ErrorEquals":["NoMoreArticles"],
                "ResultPath":"$.noMoreArticles",
                "Next":"Get Last Imported User"
              }
            ]
          },
          "Get Last Imported User":{
            "Type":"Task",
            "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-getLastImportedUser",
            "ResultPath":"$.lastImport",
            "Next":"Get Users Since Last Import"
          },
          "Get Users Since Last Import":{
            "Type":"Task",
            "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-getUsersSinceLastImport",
            "ResultPath":"$.users",
            "Next":"Migrate User",
            "Catch":[
              {
                "ErrorEquals":["NoMoreUsers"],
                "ResultPath":"$.noMoreUsers",
                "Next":"Done"
              }
            ]
          },
          "Migrate User":{
            "Type":"Map",
            "ItemsPath":"$.users",
            "ResultPath":"$.users",
            "MaxConcurrency":2,
            "Next":"Get Last Imported User",
            "Iterator":{
              "StartAt":"Migrate Favorites",
              "States":{
                "Migrate Favorites":{
                  "Type":"Task",
                  "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-migrateFavorites",
                  "ResultPath":"$.migratedFavorites",
                  "Next":"Migrate Following"
                },
                "Migrate Following":{
                  "Type":"Task",
                  "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-migrateFollowing",
                  "ResultPath":"$.migratedFavorites",
                  "Next":"User Migrated"
                },
                "User Migrated":{
                  "Type":"Task",
                  "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-userMigrated",
                  "ResultPath":"$.userMigrated",
                  "End":true
                }
              }
            }
          },
          "Done":{
            "Type":"Succeed"
          },
          "Migrate Articles":{
            "Type":"Map",
            "ItemsPath":"$.articles",
            "ResultPath":"$.articles",
            "MaxConcurrency":2,
            "Next":"Get Last Imported Article",
            "Iterator":{
              "StartAt":"Migrate Article",
              "States":{
                "Migrate Article":{
                  "Type":"Parallel",
                  "Next":"Article Migrated",
                  "ResultPath":"$.parallelResults",
                  "Branches":[
                    {
                      "StartAt":"Article",
                      "States":{
                        "Article":{
                          "Type":"Task",
                          "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-migrateArticle",
                          "End":true
                        }
                      }
                    },
                    {
                      "StartAt":"Comments",
                      "States":{
                        "Comments":{
                          "Type":"Task",
                          "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-migrateComments",
                          "End":true
                        }
                      }
                    },
                    {
                      "StartAt":"Authors",
                      "States":{
                        "Authors":{
                          "Type":"Task",
                          "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-migrateAuthors",
                          "End":true
                        }
                      }
                    },
                    {
                      "StartAt":"Tags",
                      "States":{
                        "Tags":{
                          "Type":"Task",
                          "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-migrateTags",
                          "End":true
                        }
                      }
                    }
                  ]
                },
                "Article Migrated":{
                  "Type":"Task",
                  "Resource":"arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:oif-articles-${self:provider.stage}-articleMigrated",
                  "ResultPath":"$.articleMigrated",
                  "End":true
                }
              }
            }
          }
        }
      }
    RoleArn: ${self:resources.Outputs.StepFunctionsExecutionRoleArn.Value}